### ISSUE TITLE
Dragging Delay

### ISSUE THREAD

**Issue by caioiglesias** [brendankenny/CanvasLayer#3]
I was trying to figure out why dragging the map took the canvas some time to follow it, producing a noticeable not-in-sync lag. 

It puzzled me because I was not seeing that happening on your talks on youtube. I thought it was some sort of lack of hardware acceleration on my laptop. 

I disabled the center_changed listener on the map, which was triggering this.repositionFunction_ and noticed it stopped happening on the sample hello2d, but caused some delays on displaying markers on hello_webgl. Browsed along and found your todo:

https://github.com/brendankenny/CanvasLayer/blob/gh-pages/src/CanvasLayer.js#L474-476

That's it right?

**Comment by caioiglesias** [comment]
I added a quick fix with a debounce function on the center_changed listener, which brought speed back to it.

https://jsfiddle.net/caioiglesias/pad8yua2/embedded/result/

**Comment by caioiglesias** [comment]
https://github.com/codingcampbell/CanvasLayer/commit/2dad46452be77c31e66bfff7dd6e4b0d177f06aa

**Comment by brendankenny** [comment]
Sorry this took so long for me to get to. It looks like there was a change in the Maps API in the order in which `draw` is called relative to when the map itself is moved, so the map is getting moved _after_ drawing has already occurred that frame. Unfortunately at first glance it looks like even `update` will have to move off a rAF (which @codingcampbell is doing there), but that would be kind of a pain since we'd still want to debounce with a rAF (which he isn't doing). It's also possible the Maps API is doing better here and we just need to integrate with it more fully. I'll look into it further.

**Comment by brendankenny** [comment]
Small update: good news and bad news :) The good news is that v3 moved to `requestAnimationFrame` for mouse dragging in version 3.21 (you can check this by forcing version 3.20 while it's still available...no laggy dragging), so it's totally fine to now drive `repositionCanvas_` and `update_` directly by the `center_changed` event.

The bad news is that this interacts poorly with some other parts of the current API. If you want to be continuously animated, a `requestAnimationFrame` callback would happen both for your animation and a mouse move while the user was dragging, for instance. There's no way to check if a mouse move is already queued up, and because that callback always happens _after_ the animation callback, there's no way to know if one is coming and so the first callback should be skipped. There are a couple of other corner cases where a similar thing can happen as well.

Some slightly more involved changes will be needed to work around this.

**Comment by rock7-dan** [comment]
Hey Brendan - super useful library thanks! Have you had any more thoughts about the dragging delay? At present, the lag only appears to be an issue with Safari (Chrome keeps the two in sync nicely).

**Comment by caioiglesias** [comment]
Using "bounds_changed" instead of "center_changed" cleared any dragging delays for me as of right now.

**Comment by caioiglesias** [comment]
I can only see a precise sync in Chrome when listening for bounds_changed instead of center_changed. Safari is still the same.

**Comment by donmccurdy** [comment]
I'm seeing this lag in Chrome, Firefox, Safari, and Opera. Using `bounds_changed` instead of `center_changed` fixes all but Safari, as @caioiglesias mentions.

Unfortunately I don't understand at all why that is the case. Stack traces show:

```
`mousemove` event
├── ... Maps JS API stuff ...
└── `center_changed` event
```

```
`setTimeout(..., 0)`
├── ... Maps JS API stuff ...
└── `bounds_changed` event
```

Of the two, `center_changed` would seem like the more immediate option. In another example I created [here](http://bl.ocks.org/donmccurdy/bd239cc355de227b1104503fc9d435d2), using SVG, the effect of `center_changed` vs `bounds_changed` is reversed — `center_changed` "fixes" the lag.

***

Another change that also fixes the lag would be replacing [`CanvasLayer:499`](https://github.com/brendankenny/CanvasLayer/blob/gh-pages/src/CanvasLayer.js#L499) with `this.update_()`. This fixes Safari, but triggering ~~DOM updates~~ updateHandler on every `mousemove` event seems less than ideal for performance.

**Comment by donmccurdy** [comment]
> it's totally fine to now drive repositionCanvas_ and update_ directly by the center_changed event.

@brendankenny if I understand you correctly, the downside of driving `update_` directly from the `center_changed` event is that `update_` will be invoked redundantly by the continuous animation rAF?

**Comment by brendankenny** [comment]
> the downside of driving `update_` directly from the `center_changed` event is that `update_` will be invoked redundantly by the continuous animation rAF

It's been a while, but IIRC, yes, that's the issue, and I couldn't figure out a way at the time to debounce to only one paint per frame. For the non-continuous animation mode the change would presumably be fine (again, if my memory of this is at all correct :)

**Comment by donmccurdy** [comment]
Makes sense, thanks. Digging in a bit, I don't see an obvious way to debounce this either (without literally adding a debouncing function and making assumptions about  framerate).

But, it does seem like `bounds_changed` is behaving more predictably than `center_changed`. Any reason not to switch those out, as the underlying event?
